[platformio]
src_dir = main



[env:m5stack-cores3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
framework = espidf
board = m5stack-cores3
monitor_speed = 115200
upload_speed = 1500000